version: "3"
services:
  server:
    build: server
    env_file: .env
    ports:
      - "3000:3000"
    links:
      - database
    depends_on:
      - database

  database:
    image: duluca/minimal-mongo:4.2.2
    env_file: .env
    ports:
      - "27017:27017"
    volumes:
      - "/tmp/lemon-mart-db:/data/db"
