version: '3.7'
services:
  web-app:
    image: duluca/lemon-mart-web-app
    ports:
      - '80:80'
    links:
      - server
    depends_on:
      - server

  server:
    image: duluca/lemon-mart-server
    env_file: ./server/.env
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database

  database:
    image: duluca/minimal-mongo:4.2.2
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - 'dbdata:/data/db'

volumes:
  dbdata:
