version: '3'
services:
  web-app:
    build:
      context: ./web-app
      dockerfile: nginx.Dockerfile
    ports:
      - '8080:80'
    links:
      - server
    depends_on:
      - server

  server:
    build: server
    env_file: .env
    ports:
      - '3000:3000'
    links:
      - database
    depends_on:
      - database

  database:
    image: excellalabs/mongo:4.2.0
    env_file: .env
    ports:
      - '27017:27017'
    volumes:
      - '/tmp/lemon-mart-db:/data/db'
