version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts-browsers

    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      # Update git web-app submodule
      - run: npm run webapp:update

      - run: npm run audit:ci

      - run: npm install:ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build

      - run: npm test
