version: 2.1
orbs:
  coveralls: coveralls/coveralls@1.0.4
  # Cypress Orb, see
  # https://github.com/cypress-io/circleci-orb
  cypress: cypress-io/cypress@1
jobs:
  build_server:
    docker:
      - image: circleci/node:lts
    working_directory: ~/repo/server
    steps:
      - checkout:
          path: ~/repo
      - restore_cache:
          keys:
            - v1-server-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-server-dependencies-

      # check npm dependencies for security risks - run 'npm audit' to fix
      - run: npx audit-ci --low --report-type full -w decompress

      # install dependecies
      - run: npm ci

      - save_cache:
          paths:
            - ~/.npm
          key: v1-server-dependencies-{{ checksum "package-lock.json" }}

      # ensure code formatting standards are adhered to - run 'npm run style:fix' to fix
      - run: npm run style
      - run: npm run lint

      # run tests and store test results
      - run: npm run pretest
      - run: npm run test:ci
      - store_test_results:
          path: ./test_results

      # run code coverage and store coverage report
      - run: npm run test:nyc
      - store_artifacts:
          path: ./coverage

      # upload coverage report to coveralls for readme badge support
      # requires config.yml version 2.1 and orbs: coveralls: coveralls/coveralls@1.0.4
      # requires coveralls account and token named COVERALLS_REPO_TOKEN specific to repo to be stored in CircleCI
      - coveralls/upload

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/server
            mv dist /tmp/workspace/server
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - server
  build_webapp:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo/web-app
    steps:
      - checkout:
          path: ~/repo
      - run: cd ..; npm run modules:init
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci
      - run: npx ngcc --properties es2015 --async false # async false is temp CI build fix

      # force update the webdriver, so it runs with latest version of Chrome
      - run: cd ./node_modules/protractor && npm i webdriver-manager@latest

      # because we use "npm ci" to install NPM dependencies
      # we cache "~/.npm" folder
      # because Cypress is a dev dependency
      # we should also cache "~/.cache/Cypress" folder
      - save_cache:
          paths:
            - ~/.npm
            - ~/.cache/Cypress
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm run style
      - run: npm run lint
      - run: npm run build -- --configuration=lemon-mart-server
      - run: npm test -- --watch=false --code-coverage
      - run: npm run e2e
      - run:
          name: Run Cypress tests
          command: 'npx cypress run --record'

      - store_test_results:
          path: ./test_results
      - store_artifacts:
          path: ./coverage

      - run:
          name: Tar & Gzip compiled app
          command: tar zcf dist.tar.gz dist/lemon-mart
      - store_artifacts:
          path: dist.tar.gz

      - run:
          name: Move compiled app to workspace
          command: |
            set -exu
            mkdir -p /tmp/workspace/dist
            mv dist/lemon-mart /tmp/workspace/dist/
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - dist/lemon-mart
  test_compose:
    docker:
      - image: circleci/node:lts-browsers
    working_directory: ~/repo
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: /tmp/workspace
      - checkout:
          path: ~/repo
      - run: npm run modules:init
      - run:
          name: Copy built server to server/dist folder
          command: cp -avR /tmp/workspace/server/ ./server/dist
      - run:
          name: Copy built web-app to web-app/dist folder
          command: cp -avR /tmp/workspace/dist/ ./web-app
      - run:
          name: Restore .env files
          command: |
            echo $PROJECT_DOT_ENV > .env
            echo $SERVER_DOT_ENV > server/.env
      - run:
          name: Start containers and verify there're working
          command: |
            set -x
            docker-compose up -d
workflows:
  version: 2
  build-and-test-compose:
    jobs:
      - build_server
      - build_webapp
      - test_compose:
          requires:
            - build_server
            - build_webapp
